/** Every user-visible string, so a translation only has to replace this object. */
export const en = {
  appName: "dta-learning",
  nav: {
    label: "Main",
    today: "Today",
    problems: "Problems",
    settings: "Settings",
  },
  pages: {
    today: "Today",
    solving: "Solving",
    logAttempt: "Log attempt",
    problems: "Problems",
    problemDetail: "Problem",
    settings: "Settings & data",
  },
  placeholder: "This screen is on its way.",
  separator: " · ",
  today: {
    counters: { due: "Due", newLeft: "New left", mastered: "Mastered" },
    dueReviews: "Due reviews",
    focus: "★ Focus · most at risk",
    upNext: "★ Up next",
    firstProblem: "★ Your first problem",
    newSection: "New",
    start: "Start",
    dueToday: "due today",
    daysOverdue: (days: number) => (days === 1 ? "1 day overdue" : `${days} days overdue`),
    nothingDue: "No reviews due today. A good day for something new.",
    backlogNote:
      "Welcome back. Overdue reviews carry no penalty: each one's schedule restarts from the day you do it. Start with the focus, and the order takes care of the rest.",
    showOthers: (count: number) =>
      count === 1 ? "Show the other due review" : `Show the other ${count} due reviews`,
    caughtUp: "All caught up",
    caughtUpDetail: "Every problem is started, and nothing is due today.",
    nextReview: "Next review",
    inDays: (days: number) => (days === 1 ? "in 1 day" : `in ${days} days`),
    everythingMastered: "Everything mastered",
    everythingMasteredDetail:
      "Nothing is scheduled any more. You can still practice any problem from Problems; rating it Medium or Hard puts it back in the rotation.",
    openProblems: "Open Problems",
    browseAll: (count: number) => `Browse all ${count} problems`,
    intro: {
      title: "Re-solve problems right before you forget them.",
      summary:
        "Solve a problem once, log how hard it felt, and the app brings it back just before it fades.",
      steps: ["Solve it on NeetCode", "Log it in 30 seconds", "Re-solve it from scratch later"],
      interval: (days: number) => `${days} days`,
      markSolved: "Already solved some? Mark them in Problems",
      importData: "Have an export? Import it in Settings",
    },
  },
  problems: {
    summary: (started: number, mastered: number, total: number) =>
      `${started} started · ${mastered} mastered · ${total} total`,
    filterLabel: "Filter",
    filters: { all: "All", due: "Due", new: "New", mastered: "Mastered" },
    topicDue: (count: number) => `${count} due`,
    topicMastered: (count: number) => `${count} mastered`,
    topicProgress: (done: number, total: number) => `${done} of ${total} started or mastered`,
    columns: { problem: "Problem", lastRating: "Last rating", next: "Next", status: "Status" },
    actionsColumn: "Actions",
    statuses: { new: "New", scheduled: "Scheduled", due: "Due", mastered: "Mastered" },
    upNext: "up next",
    dueToday: "today",
    noValue: "—",
    actionsFor: (title: string) => `Actions for ${title}`,
    startNow: "Start now",
    openDetails: "Open details",
    markMastered: "Mark as already mastered…",
    confirmTitle: (title: string) => `Mark ${title} as mastered?`,
    confirmLeaves:
      "It leaves the rotation and won't appear on Today again. Use this for problems you could already solve before using the app.",
    confirmUndo:
      "Changed your mind later? Delete the mark from the problem's history and its schedule comes back exactly as it was.",
    cancel: "Cancel",
    confirm: "Mark as mastered",
    empty: {
      due: "Nothing is due today.",
      new: "Every problem is started.",
      mastered: "Nothing is mastered yet.",
    },
  },
  problemDetail: {
    backToProblems: "All problems",
    dueToday: "due today",
    nextDue: (date: string) => `next ${date}`,
    start: "Start",
    neetCode: "NeetCode",
    leetCode: "LeetCode",
    markMastered: "Mark as already mastered",
    spoilerTitle: "Hidden until you log this review",
    earlierInsights: (count: number) =>
      count === 1 ? "1 earlier insight" : `${count} earlier insights`,
    hiddenWithPattern: (insights: string) =>
      `Pattern, ${insights}, solution and video. Recognizing the pattern yourself is what this review trains.`,
    hiddenWithoutPattern: (insights: string) => `${insights}, solution and video.`,
    reveal: "Reveal (spoilers)",
    hide: "Hide spoilers",
    solutionAndVideo: "Solution & video",
    solutionLink: "Solution on NeetCode",
    videoLink: "Video explanation",
    history: (attemptCount: number) =>
      attemptCount === 1 ? "History · 1 attempt" : `History · ${attemptCount} attempts`,
    timeTrend: (firstMinutes: number, latestMinutes: number) =>
      `${firstMinutes} → ${latestMinutes} min`,
    noHistory: "No attempts yet. Start it to log the first one.",
    minutes: (minutes: number) => `${minutes} min`,
    helps: { none: "No help", hint: "Hint", solution: "Looked at the solution" },
    firstTry: "First try",
    insightHidden: "Insight hidden until you log this review.",
    markedMastered: "Marked as already mastered",
    deleteAttempt: (date: string) => `Delete the ${date} attempt`,
    deleteMark: (date: string) => `Delete the ${date} mastered mark`,
    deleteTitle: (label: string) => `${label}?`,
    deleteDetail: "The schedule is recalculated from the entries left.",
    deleteNote:
      "Deleting an entry asks first, then recalculates the schedule from the entries left.",
    cancel: "Cancel",
    confirmDelete: "Delete",
  },
  ratings: { hard: "Hard", medium: "Medium", easy: "Easy" },
  solving: {
    backToToday: "‹ Today",
    reviewBadge: "Review · pattern hidden",
    reviewBadgePatternShown: "Review",
    newBadge: "New problem",
    lastSolved: (date: string) => `last solved ${date}`,
    openOnNeetCode: "Open on NeetCode",
    leetCode: "LeetCode",
    timeBoxOf: (duration: string) => `of ${duration}`,
    timeBoxCaption: {
      Easy: "Time box for an Easy problem. It's guidance, not a deadline.",
      Medium: "Time box for a Medium problem. It's guidance, not a deadline.",
      Hard: "Time box for a Hard problem. It's guidance, not a deadline.",
    },
    overTimeBox: (minutes: number) =>
      `${minutes} min past the time box. Keep going, or log it as it is.`,
    reviewTip: "Don't use NeetCode's list or prev/next arrows. They reveal the pattern.",
    done: "I'm done",
    lookedAtSolution: "I looked at the solution",
    cancel: "Cancel",
    replaceTimer: (title: string) => `Replace the running timer for ${title}?`,
    replace: "Replace it",
    keepOther: (title: string) => `Keep it and go back to ${title}`,
    notFound: "This problem isn't in the list.",
  },
  log: {
    backToTimer: "‹ Back to the timer",
    label: "Log attempt",
    ratingLegend: "How did it feel?",
    intervalDays: (days: number) => `+${days} days`,
    anchors: {
      hard: "I needed the solution or a big hint, couldn't finish, or went way over the time box.",
      medium:
        "I solved it on my own, but it was a struggle: slow to find the approach, several bugs, or over the time box.",
      easy: "I saw the approach quickly and wrote a working solution within the time box.",
    },
    time: "Time",
    minutesSuffix: "min",
    fromTimer: "From the timer",
    helpLegend: "Help used",
    helps: { none: "None", hint: "Hint", solution: "Solution" },
    keyInsight: "Key insight",
    keyInsightPlaceholder: "What's the trick? How would I recognize it next time?",
    keyInsightHint: "You'll see this after your next attempt.",
    notes: "Notes",
    addNotes: "+ Add notes",
    save: "Save",
    saveShortcut: "Ctrl+Enter",
    ratingRequired: "Choose how it felt.",
    timeInvalid: (min: number, max: number) => `Enter the time in minutes, from ${min} to ${max}.`,
    logged: (rating: string) => `Logged · ${rating}`,
    nextResolve: (date: string) => `Next re-solve: ${date}`,
    mastered: "Mastered!",
    masteredDetail:
      "Easy again, 30 days after an Easy. It leaves the rotation. Rate it Medium or Hard on any later practice and it comes back.",
    masteredCount: (count: number, total: number) => `${count} of ${total} mastered`,
    nowRevealed: "Now revealed",
    lastTime: (date: string) => `Last time · ${date}`,
    todayColumn: "Today",
    minutes: (minutes: number) => `${minutes} min`,
    sameTime: "same time",
    faster: (minutes: number) => `${minutes} min faster`,
    slower: (minutes: number) => `${minutes} min slower`,
    solutionLink: "Solution on NeetCode",
    videoLink: "Video explanation",
    backToToday: "Back to Today",
    undo: "Undo",
  },
  opensInNewTab: "(opens in a new tab)",
  documentTitle: (page: string) => `${page} · dta-learning`,
} as const;

export const t = en;
