import type { Problem } from "@/domain/types";

import problemsJson from "./problems.json";

/** The NeetCode 150 in NeetCode's order. Generated by scripts/build-problems.ts; see NOTICE.md. */
export const PROBLEMS: Problem[] = problemsJson as Problem[]; // safe: problems.test.ts checks it
